<template>
  <div class="item-list">
    <div
      v-for="item in componentList.filter((data) =>
        data.label.toLowerCase().includes(filterText.toLowerCase())
      )"
      :key="item.id"
      class="item"
    >
      <div class="preview" draggable @dragstart="handleDragStart($event, item)">
        <img
          v-if="!item.online"
          draggable="false"
          :src="require(`./images/${item.img}`)"
          alt=""
        />
        <img v-else draggable="false" :src="item.img" alt="" />
      </div>
      <span class="title">{{ item.label }}</span>
    </div>
  </div>
</template>

<script>
import * as componentAPI from "@/apis/component";
export default {
  props: ["typeData", "filterText"],
  data() {
    return {
      componentList: [],
      componentEnum: [
        {
          // 基础组件
          typeName: "布局",
          list: [
            {
              id: "6",
              type: "component",
              name: "WContainer",
              label: "盒子",
              img: "01布局-盒子.jpg",
            },
            {
              id: "1",
              type: "config",
              config: {
                id: "C54wMW7rsr6q9td1CChwU",
                name: "WContainer",
                children: [
                  {
                    id: "4gIS4Sx2KT2F_hLBf6ShL",
                    name: "WContainer",
                    children: [],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "block",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "none",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "auto",
                        gridRowEnd: "auto",
                        gridColumnStart: "auto",
                        gridColumnEnd: "auto",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                  {
                    id: "kF75H8yFgGQuEl5ty4rc3",
                    name: "WContainer",
                    children: [],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "block",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "none",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "auto",
                        gridRowEnd: "auto",
                        gridColumnStart: "auto",
                        gridColumnEnd: "auto",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                ],
                slot: "default",
                options: {
                  title: "容器",
                },
                slotName: "default",
                attribs: {
                  style: {
                    width: "100%",
                    height: "100%",
                    backgroundColor: "rgba(255, 255, 255, 1)",
                    padding: "0",
                    margin: "0",
                    overflow: "visible",
                    display: "grid",
                    alignItems: "stretch",
                    alignContent: "stretch",
                    justifyItems: "stretch",
                    justifyContent: "stretch",
                    gridTemplateColumns: "none",
                    gridTemplateRows: "1fr 1fr",
                    columnGap: "0",
                    rowGap: "0",
                    gridAutoFlow: "row",
                    gridRowStart: "auto",
                    gridRowEnd: "auto",
                    gridColumnStart: "auto",
                    gridColumnEnd: "auto",
                    justifySelf: "stretch",
                    alignSelf: "stretch",
                  },
                },
                datas: [],
                events: [],
                show: true,
              },
              label: "上下布局",
              img: "03布局-上下.jpg",
            },
            {
              id: "2",
              type: "config",
              config: {
                id: "C54wMW7rsr6q9td1CChwU",
                name: "WContainer",
                children: [
                  {
                    id: "4gIS4Sx2KT2F_hLBf6ShL",
                    name: "WContainer",
                    children: [],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "block",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "none",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "auto",
                        gridRowEnd: "auto",
                        gridColumnStart: "auto",
                        gridColumnEnd: "auto",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                  {
                    id: "kF75H8yFgGQuEl5ty4rc3",
                    name: "WContainer",
                    children: [],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "block",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "none",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "auto",
                        gridRowEnd: "auto",
                        gridColumnStart: "auto",
                        gridColumnEnd: "auto",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                ],
                slot: "default",
                options: {
                  title: "容器",
                },
                slotName: "default",
                attribs: {
                  style: {
                    width: "100%",
                    height: "100%",
                    backgroundColor: "rgba(255, 255, 255, 1)",
                    padding: "0",
                    margin: "0",
                    overflow: "visible",
                    display: "grid",
                    alignItems: "stretch",
                    alignContent: "stretch",
                    justifyItems: "stretch",
                    justifyContent: "stretch",
                    gridTemplateColumns: "1fr 1fr",
                    gridTemplateRows: "none",
                    columnGap: "0",
                    rowGap: "0",
                    gridAutoFlow: "row",
                    gridRowStart: "auto",
                    gridRowEnd: "auto",
                    gridColumnStart: "auto",
                    gridColumnEnd: "auto",
                    justifySelf: "stretch",
                    alignSelf: "stretch",
                  },
                },
                datas: [],
                events: [],
                show: true,
              },
              label: "左右布局",
              img: "02布局-左右.jpg",
            },
            {
              id: "3",
              type: "config",
              config: {
                id: "C54wMW7rsr6q9td1CChwU",
                name: "WContainer",
                children: [
                  {
                    id: "4gIS4Sx2KT2F_hLBf6ShL",
                    name: "WContainer",
                    children: [],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "block",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "none",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "auto",
                        gridRowEnd: "auto",
                        gridColumnStart: "auto",
                        gridColumnEnd: "auto",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                  {
                    id: "kF75H8yFgGQuEl5ty4rc3",
                    name: "WContainer",
                    children: [],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "block",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "none",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "auto",
                        gridRowEnd: "auto",
                        gridColumnStart: "auto",
                        gridColumnEnd: "auto",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                  {
                    id: "FF75H8yFgGUuEl5ty4Vc4",
                    name: "WContainer",
                    children: [],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "block",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "none",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "auto",
                        gridRowEnd: "auto",
                        gridColumnStart: "auto",
                        gridColumnEnd: "auto",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                  {
                    id: "h475H8yJgGQull5ty7Hdf",
                    name: "WContainer",
                    children: [],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "block",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "none",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "auto",
                        gridRowEnd: "auto",
                        gridColumnStart: "auto",
                        gridColumnEnd: "auto",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                ],
                slot: "default",
                options: {
                  title: "容器",
                },
                slotName: "default",
                attribs: {
                  style: {
                    width: "100%",
                    height: "100%",
                    backgroundColor: "rgba(255, 255, 255, 1)",
                    padding: "0",
                    margin: "0",
                    overflow: "visible",
                    display: "grid",
                    alignItems: "stretch",
                    alignContent: "stretch",
                    justifyItems: "stretch",
                    justifyContent: "stretch",
                    gridTemplateColumns: "1fr 1fr",
                    gridTemplateRows: "1fr 1fr",
                    columnGap: "0",
                    rowGap: "0",
                    gridAutoFlow: "row",
                    gridRowStart: "auto",
                    gridRowEnd: "auto",
                    gridColumnStart: "auto",
                    gridColumnEnd: "auto",
                    justifySelf: "stretch",
                    alignSelf: "stretch",
                  },
                },
                datas: [],
                events: [],
                show: true,
              },
              label: "田字布局",
              img: "04布局-田.jpg",
            },
            {
              id: "4",
              type: "config",
              config: {
                id: "MxkmUPh_q9pqxkw8yG-4F",
                name: "WContainer",
                children: [
                  {
                    id: "ajLAn1CB3JExiQixtv7OW",
                    name: "WContainer",
                    children: [],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "block",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "none",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "auto",
                        gridRowEnd: "auto",
                        gridColumnStart: "auto",
                        gridColumnEnd: "auto",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                  {
                    id: "fOKlE10oNXF5RTI0iNaL_",
                    name: "WContainer",
                    children: [],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "block",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "none",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "1",
                        gridRowEnd: "3",
                        gridColumnStart: "2",
                        gridColumnEnd: "3",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                  {
                    id: "UWxO-5W41wYqajx7sCaI_",
                    name: "WContainer",
                    children: [],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "block",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "none",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "auto",
                        gridRowEnd: "auto",
                        gridColumnStart: "auto",
                        gridColumnEnd: "auto",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                  {
                    id: "QzapIwg4wzt1tzWcvC8wk",
                    name: "WContainer",
                    children: [],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "block",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "none",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "auto",
                        gridRowEnd: "auto",
                        gridColumnStart: "auto",
                        gridColumnEnd: "auto",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                  {
                    id: "e4qJkINk4hWVCgO5UHNlp",
                    name: "WContainer",
                    children: [],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "block",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "none",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "auto",
                        gridRowEnd: "auto",
                        gridColumnStart: "auto",
                        gridColumnEnd: "auto",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                  {
                    id: "CBTtbHRpjRd6iZiC6lS1R",
                    name: "WContainer",
                    children: [],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "block",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "none",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "auto",
                        gridRowEnd: "auto",
                        gridColumnStart: "auto",
                        gridColumnEnd: "auto",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                  {
                    id: "fvEYtyfNd3lmqscNTLwuJ",
                    name: "WContainer",
                    children: [],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "block",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "none",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "auto",
                        gridRowEnd: "auto",
                        gridColumnStart: "auto",
                        gridColumnEnd: "auto",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                  {
                    id: "nCBWZKcoR0yGxjGECfrST",
                    name: "WContainer",
                    children: [],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "block",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "none",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "auto",
                        gridRowEnd: "auto",
                        gridColumnStart: "auto",
                        gridColumnEnd: "auto",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                ],
                slot: "default",
                options: {
                  title: "容器",
                },
                slotName: "default",
                attribs: {
                  style: {
                    width: "100%",
                    height: "100%",
                    backgroundColor: "rgba(255, 255, 255, 1)",
                    padding: "0",
                    margin: "0",
                    overflow: "visible",
                    display: "grid",
                    alignItems: "stretch",
                    alignContent: "stretch",
                    justifyItems: "stretch",
                    justifyContent: "stretch",
                    gridTemplateColumns: "1fr 1fr 1fr",
                    gridTemplateRows: "1fr 1fr 1fr",
                    columnGap: "0",
                    rowGap: "0",
                    gridAutoFlow: "row",
                    gridRowStart: "auto",
                    gridRowEnd: "auto",
                    gridColumnStart: "auto",
                    gridColumnEnd: "auto",
                    justifySelf: "stretch",
                    alignSelf: "stretch",
                  },
                },
                datas: [],
                events: [],
                show: true,
              },
              label: "3-2-3 布局",
              img: "06布局3-2-3.jpg",
            },
            {
              id: "5",
              type: "config",
              config: {
                id: "BQeg8oYPww0MVVbnGoUei",
                name: "WContainer",
                children: [
                  {
                    id: "jFTf7q6mjdcDB8ldQMNrO",
                    name: "WContainer",
                    children: [],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "block",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "none",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "auto",
                        gridRowEnd: "auto",
                        gridColumnStart: "auto",
                        gridColumnEnd: "auto",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                  {
                    id: "6icn1WpY9Tft_C5buwnqq",
                    name: "WContainer",
                    children: [
                      {
                        id: "cjgIIGdBCMEup4QAppwHZ",
                        name: "WContainer",
                        children: [],
                        slot: "default",
                        options: {
                          title: "容器",
                        },
                        slotName: "default",
                        attribs: {
                          style: {
                            width: "100%",
                            height: "100%",
                            backgroundColor: "rgba(255, 255, 255, 1)",
                            padding: "0",
                            margin: "0",
                            overflow: "visible",
                            display: "block",
                            alignItems: "stretch",
                            alignContent: "stretch",
                            justifyItems: "stretch",
                            justifyContent: "stretch",
                            gridTemplateColumns: "none",
                            gridTemplateRows: "none",
                            columnGap: "0",
                            rowGap: "0",
                            gridAutoFlow: "row",
                            gridRowStart: "auto",
                            gridRowEnd: "auto",
                            gridColumnStart: "auto",
                            gridColumnEnd: "auto",
                            justifySelf: "stretch",
                            alignSelf: "stretch",
                          },
                        },
                        datas: [],
                        events: [],
                        show: true,
                      },
                      {
                        id: "JwXuRlqkXFSWOmCK8WYt6",
                        name: "WContainer",
                        children: [],
                        slot: "default",
                        options: {
                          title: "容器",
                        },
                        slotName: "default",
                        attribs: {
                          style: {
                            width: "100%",
                            height: "100%",
                            backgroundColor: "rgba(255, 255, 255, 1)",
                            padding: "0",
                            margin: "0",
                            overflow: "visible",
                            display: "block",
                            alignItems: "stretch",
                            alignContent: "stretch",
                            justifyItems: "stretch",
                            justifyContent: "stretch",
                            gridTemplateColumns: "none",
                            gridTemplateRows: "none",
                            columnGap: "0",
                            rowGap: "0",
                            gridAutoFlow: "row",
                            gridRowStart: "auto",
                            gridRowEnd: "auto",
                            gridColumnStart: "auto",
                            gridColumnEnd: "auto",
                            justifySelf: "stretch",
                            alignSelf: "stretch",
                          },
                        },
                        datas: [],
                        events: [],
                        show: true,
                      },
                    ],
                    slot: "default",
                    options: {
                      title: "容器",
                    },
                    slotName: "default",
                    attribs: {
                      style: {
                        width: "100%",
                        height: "100%",
                        backgroundColor: "rgba(255, 255, 255, 1)",
                        padding: "0",
                        margin: "0",
                        overflow: "visible",
                        display: "grid",
                        alignItems: "stretch",
                        alignContent: "stretch",
                        justifyItems: "stretch",
                        justifyContent: "stretch",
                        gridTemplateColumns: "none",
                        gridTemplateRows: "50px 1fr",
                        columnGap: "0",
                        rowGap: "0",
                        gridAutoFlow: "row",
                        gridRowStart: "auto",
                        gridRowEnd: "auto",
                        gridColumnStart: "auto",
                        gridColumnEnd: "auto",
                        justifySelf: "stretch",
                        alignSelf: "stretch",
                      },
                    },
                    datas: [],
                    events: [],
                    show: true,
                  },
                ],
                slot: "default",
                options: {
                  title: "容器",
                },
                slotName: "default",
                attribs: {
                  style: {
                    width: "100%",
                    height: "100%",
                    backgroundColor: "rgba(255, 255, 255, 1)",
                    padding: "0",
                    margin: "0",
                    overflow: "visible",
                    display: "grid",
                    alignItems: "stretch",
                    alignContent: "stretch",
                    justifyItems: "stretch",
                    justifyContent: "stretch",
                    gridTemplateColumns: "200px 1fr",
                    gridTemplateRows: "none",
                    columnGap: "0",
                    rowGap: "0",
                    gridAutoFlow: "row",
                    gridRowStart: "auto",
                    gridRowEnd: "auto",
                    gridColumnStart: "auto",
                    gridColumnEnd: "auto",
                    justifySelf: "stretch",
                    alignSelf: "stretch",
                  },
                },
                datas: [],
                events: [],
                show: true,
              },
              label: "1-2 布局",
              img: "05布局1-2.jpg",
            },
          ],
        },
        {
          typeName: "折线图",
          list: [
            {
              id: "8",
              type: "component",
              name: "WLine",
              label: "折线图",
              img: "12折线图.jpg",
            },
          ],
        },
        {
          typeName: "条形图",
          list: [
            {
              id: "9",
              type: "component",
              name: "WBar",
              label: "条形图",
              img: "15条形图.jpg",
            },
          ],
        },
        {
          typeName: "饼图",
          list: [
            {
              id: "10",
              type: "component",
              name: "WPie",
              label: "饼图",
              img: "13饼形.jpg",
            },
          ],
        },
        {
          typeName: "按钮",
          list: [
            {
              id: "2",
              type: "component",
              name: "WButton",
              label: "按钮",
              img: "10按钮.jpg",
            },
          ],
        },
        {
          typeName: "表格",
          list: [
            {
              id: "3",
              type: "component",
              name: "WTable",
              label: "表格",
              img: "08表格.jpg",
            },
          ],
        },
        {
          typeName: "分页",
          list: [
            {
              id: "4",
              type: "component",
              name: "WPagination",
              label: "分页",
              img: "16分页.jpg",
            },
          ],
        },
        {
          typeName: "图片",
          list: [{ id: "6", type: "component", name: "WImage", label: "图片" }],
        },
        {
          typeName: "标签页",
          list: [
            {
              id: "7",
              type: "component",
              name: "WTabs",
              label: "标签页",
              img: "09标签.jpg",
            },
          ],
        },
        {
          typeName: "文字",
          list: [
            {
              id: "11",
              type: "component",
              name: "WText",
              label: "文字",
              img: "07文字.jpg",
            },
          ],
        },
        {
          typeName: "分割线",
          list: [
            {
              id: "12",
              type: "component",
              name: "WStreak",
              label: "线条",
              img: "14分割线.jpg",
            },
          ],
        },
        {
          typeName: "输入框",
          list: [
            {
              id: "13",
              type: "component",
              name: "WInput",
              label: "输入框",
              img: "11输入框.jpg",
            },
          ],
        },
      ],
    };
  },
  created() {
    this.getData();
  },
  methods: {
    async getData() {
      let eData = this.componentEnum.find(
        (obj) => obj.typeName == this.typeData.name
      );
      if (eData) {
        this.componentList = eData.list;
      } else {
        this.componentList = [];
      }
      try {
        const res = await componentAPI.getByCat({
          id: this.typeData.id,
          name: "",
          page_index: 0,
          page_size: 0,
        });
        if (res.code === 200) {
          this.componentList = [
            ...this.componentList.map((obj) => ({ ...obj, online: false })),
            ...res.data.list.map((obj) => ({
              ...obj,
              type: "component",
              name: obj.code,
              label: obj.name,
              online: true,
              img: "/resource_file/" + obj.preview_url,
            })),
          ];
          console.log(this.componentList);
        }
      } catch (error) {
        //
      }
    },
    // 处理开始拖拽事件
    handleDragStart(e, data) {
      if (data.type === "component") {
        e.dataTransfer.setData(
          "dragData",
          JSON.stringify({
            type: "add",
            name: data.name,
          })
        );
      } else if (data.type === "config") {
        e.dataTransfer.setData(
          "dragData",
          JSON.stringify({
            type: "addConfig",
            config: data.config,
          })
        );
      }
    },
  },
};
</script>

<style lang="scss" scoped>
@import "./index.scss";
</style>
